/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lekha khobrekar
 */
import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EmployeeSalary extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeSalary
     */
    
    Connection con;
    ResultSet rs;
    Statement st;
    PreparedStatement ps;
    
    public EmployeeSalary() {
        initComponents();
        DBConnect dbc=new DBConnect();
        con=dbc.Connect();
        System.out.println("DB Connected");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ENameL = new javax.swing.JLabel();
        ENameTF = new javax.swing.JTextField();
        AnalyseB = new javax.swing.JButton();
        DetailsL = new javax.swing.JLabel();
        EIdL = new javax.swing.JLabel();
        EName2L = new javax.swing.JLabel();
        EIdTF = new javax.swing.JTextField();
        EName2TF = new javax.swing.JTextField();
        EPostL = new javax.swing.JLabel();
        EPostTF = new javax.swing.JTextField();
        ESalaryL = new javax.swing.JLabel();
        ESalaryTF = new javax.swing.JTextField();
        HomeB = new javax.swing.JButton();
        ResetB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Salary", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 1, 20))); // NOI18N

        ENameL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        ENameL.setText("Employee Name");

        ENameTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N

        AnalyseB.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        AnalyseB.setText("Analyse");
        AnalyseB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyseBActionPerformed(evt);
            }
        });

        DetailsL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        DetailsL.setText("Details:");

        EIdL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EIdL.setText("Employee ID");

        EName2L.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EName2L.setText("Employee Name");

        EIdTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N

        EName2TF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EName2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EName2TFActionPerformed(evt);
            }
        });

        EPostL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EPostL.setText("Employee Post");

        EPostTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N

        ESalaryL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        ESalaryL.setText("Employee Salary");

        ESalaryTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N

        HomeB.setText("Home");
        HomeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBActionPerformed(evt);
            }
        });

        ResetB.setText("Reset");
        ResetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ResetB)
                        .addGap(18, 18, 18)
                        .addComponent(HomeB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ENameL)
                                .addGap(18, 18, 18)
                                .addComponent(ENameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DetailsL)
                                    .addComponent(ESalaryL)
                                    .addComponent(EName2L)
                                    .addComponent(EPostL)
                                    .addComponent(EIdL))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EName2TF, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ESalaryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EPostTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(106, 106, 106)
                        .addComponent(AnalyseB)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ENameL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ENameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnalyseB))
                .addGap(30, 30, 30)
                .addComponent(DetailsL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EIdL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EName2L, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EName2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EPostL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EPostTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ESalaryL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ESalaryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeB)
                    .addComponent(ResetB))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EName2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EName2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EName2TFActionPerformed

    private void HomeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HRManagement HR= new HRManagement();
        HR.setLocationRelativeTo(null);
        HR.setTitle("HR Management System");
        HR.setVisible(true);
    }//GEN-LAST:event_HomeBActionPerformed

    private void AnalyseBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyseBActionPerformed
        // TODO add your handling code here:
        EmployeeSalary.Function f1=new EmployeeSalary.Function();
            rs=null;
            rs=f1.find(ENameTF.getText());
            
            int ID=0;
            String Name="";
            String Post="";
            String Salary="";
            

        try{
            
            if(rs.next())
            {
                    ID=Integer.parseInt(rs.getString("empId"));
                    Name=rs.getString("empName");
                    Post=rs.getString("empPOST");
                    Salary=rs.getString("empSalary");
                    
                    EIdTF.setText(String.valueOf(ID));
                    EName2TF.setText(Name);
                    EPostTF.setText(Post);
                    ESalaryTF.setText(Salary);
            }   
            else
            {
                System.out.println("NO DATA");
            }
        }
        catch(Exception e){
            System.out.println("Exception:"+e.getMessage());
        }
    }//GEN-LAST:event_AnalyseBActionPerformed

    private void ResetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBActionPerformed
        // TODO add your handling code here:
        ENameTF.setText("");
        EIdTF.setText("");
        EName2TF.setText("");
        EPostTF.setText("");
        ESalaryTF.setText("");
    }//GEN-LAST:event_ResetBActionPerformed

    public class Function
    {
        public ResultSet find(String s)
        {
            try{
            st = con.createStatement();
            ps=con.prepareStatement("select empId,empName,empPOST,empSalary from employee where empName = ?");
            ps.setString(1,s);
            rs = ps.executeQuery();
            }
            catch(Exception e)
            {
                System.out.println(e.getMessage());
            }
           return rs;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalyseB;
    private javax.swing.JLabel DetailsL;
    private javax.swing.JLabel EIdL;
    private javax.swing.JTextField EIdTF;
    private javax.swing.JLabel EName2L;
    private javax.swing.JTextField EName2TF;
    private javax.swing.JLabel ENameL;
    private javax.swing.JTextField ENameTF;
    private javax.swing.JLabel EPostL;
    private javax.swing.JTextField EPostTF;
    private javax.swing.JLabel ESalaryL;
    private javax.swing.JTextField ESalaryTF;
    private javax.swing.JButton HomeB;
    private javax.swing.JButton ResetB;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
