/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lekha khobrekar
 */
import javax.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

public class HRManagement extends javax.swing.JFrame {

    /**
     * Creates new form HRManagement
     */
    public HRManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddEmployeeB = new javax.swing.JButton();
        SearchEmployeeB = new javax.swing.JButton();
        UpdateEmployeeB = new javax.swing.JButton();
        SalaryB = new javax.swing.JButton();
        SkillsB = new javax.swing.JButton();
        LoginB1 = new javax.swing.JButton();
        LogoutB1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HR Management System", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Serif", 1, 20))); // NOI18N

        AddEmployeeB.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        AddEmployeeB.setText("New Employee");
        AddEmployeeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeBActionPerformed(evt);
            }
        });

        SearchEmployeeB.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        SearchEmployeeB.setText("Search Employee");
        SearchEmployeeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEmployeeBActionPerformed(evt);
            }
        });

        UpdateEmployeeB.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        UpdateEmployeeB.setText("Update Employee");
        UpdateEmployeeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeBActionPerformed(evt);
            }
        });

        SalaryB.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        SalaryB.setText("Salary");
        SalaryB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryBActionPerformed(evt);
            }
        });

        SkillsB.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        SkillsB.setText("Skills");
        SkillsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkillsBActionPerformed(evt);
            }
        });

        LoginB1.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        LoginB1.setText("Login");
        LoginB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginB1ActionPerformed(evt);
            }
        });

        LogoutB1.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        LogoutB1.setText("Logout");
        LogoutB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoutB1)
                    .addComponent(SkillsB)
                    .addComponent(UpdateEmployeeB)
                    .addComponent(SearchEmployeeB)
                    .addComponent(SalaryB)
                    .addComponent(AddEmployeeB)
                    .addComponent(LoginB1))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(AddEmployeeB)
                .addGap(18, 18, 18)
                .addComponent(SearchEmployeeB)
                .addGap(18, 18, 18)
                .addComponent(UpdateEmployeeB)
                .addGap(18, 18, 18)
                .addComponent(SalaryB)
                .addGap(18, 18, 18)
                .addComponent(SkillsB)
                .addGap(18, 18, 18)
                .addComponent(LoginB1)
                .addGap(18, 18, 18)
                .addComponent(LogoutB1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateEmployeeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        UpdateEmployee UpdateEmp= new UpdateEmployee();
        UpdateEmp.setLocationRelativeTo(null);
        UpdateEmp.setTitle("UPDATE EMPLOYEE");
        UpdateEmp.setVisible(true);
    }//GEN-LAST:event_UpdateEmployeeBActionPerformed

    private void SearchEmployeeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEmployeeBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SearchEmployee SearchEmp= new SearchEmployee();
        SearchEmp.setLocationRelativeTo(null);
        SearchEmp.setTitle("SEARCH EMPLOYEE");
        SearchEmp.setVisible(true);
    }//GEN-LAST:event_SearchEmployeeBActionPerformed

    private void AddEmployeeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        NewEmployee NewEmp= new NewEmployee();
        NewEmp.setLocationRelativeTo(null);
        NewEmp.setTitle("NEW EMPLOYEE");
        NewEmp.setVisible(true);
    }//GEN-LAST:event_AddEmployeeBActionPerformed

    private void SkillsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkillsBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        EmployeeSkills S1= new EmployeeSkills();
        S1.setLocationRelativeTo(null);
        S1.setTitle("EMPLOYEE SKILLS");
        S1.setVisible(true);
    }//GEN-LAST:event_SkillsBActionPerformed

    private void SalaryBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryBActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        EmployeeSalary Salary= new EmployeeSalary();
        Salary.setLocationRelativeTo(null);
        Salary.setTitle("EMPLOYEE SKILLS");
        Salary.setVisible(true);
    }//GEN-LAST:event_SalaryBActionPerformed

    private void LoginB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginB1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login L1= new Login();
        L1.setLocationRelativeTo(null);
        L1.setTitle("LOGIN");
        L1.setVisible(true);
    }//GEN-LAST:event_LoginB1ActionPerformed

    private void LogoutB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutB1ActionPerformed
        // TODO add your handling code here:
        //dispose();
        System.exit(0);
    }//GEN-LAST:event_LogoutB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployeeB;
    private javax.swing.JButton LoginB1;
    private javax.swing.JButton LogoutB1;
    private javax.swing.JButton SalaryB;
    private javax.swing.JButton SearchEmployeeB;
    private javax.swing.JButton SkillsB;
    private javax.swing.JButton UpdateEmployeeB;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
