/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lekha khobrekar
 */

import java.awt.event.*;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.io.*;

public class Login extends javax.swing.JFrame {
    
    Connection con;
    ResultSet rs;
    Statement st;

    /**
     * Creates new form Login
     */
    public Login() {
       initComponents();
      
       this.getRootPane().setDefaultButton(LoginB);
       try
       {
       con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hrmanagement","root", "");
       System.out.println("Database connection successful");
            st = con.createStatement();
       }
       catch(Exception e) {System.out.println("Exception Generated:"+e);}
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AdminIdL = new javax.swing.JLabel();
        PasswordL = new javax.swing.JLabel();
        AdminIdTF = new javax.swing.JTextField();
        PasswordTF = new javax.swing.JPasswordField();
        LoginB = new javax.swing.JButton();
        ResetB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 1, 20))); // NOI18N

        AdminIdL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        AdminIdL.setText("Admin ID");

        PasswordL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        PasswordL.setText("Password");

        AdminIdTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        AdminIdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminIdTFActionPerformed(evt);
            }
        });

        PasswordTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        PasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTFActionPerformed(evt);
            }
        });

        LoginB.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        LoginB.setText("Login");
        LoginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBActionPerformed(evt);
            }
        });

        ResetB.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        ResetB.setText("Reset");
        ResetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PasswordL)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(AdminIdL)
                                .addGap(21, 21, 21)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AdminIdTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(PasswordTF))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 202, Short.MAX_VALUE)
                        .addComponent(LoginB)
                        .addGap(18, 18, 18)
                        .addComponent(ResetB)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminIdL)
                    .addComponent(AdminIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordL)
                    .addComponent(PasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginB)
                    .addComponent(ResetB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminIdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminIdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminIdTFActionPerformed

    private void LoginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBActionPerformed
        // TODO add your handling code here:
        
        if(AdminIdTF.getText().equals("") || PasswordTF.getText().equals("") )
        {
            JOptionPane.showMessageDialog(this, "Please enter username and/or password",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try{
                st = con.createStatement();
                String sqlstr="select * from login where "+ "name='"+AdminIdTF.getText()+"' and password='"+ PasswordTF.getText()+"'";
                rs = st.executeQuery(sqlstr);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this,"Login Successful!!!");
                    // System.out.println("Button pressed");
                }
                else
                {
                 JOptionPane.showMessageDialog(this, "Invalid Credentials!!!",
                "Login Failed", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
                }    
                this.setVisible(false) ;
                HRManagement HR = new HRManagement() ;
                HR.setLocationRelativeTo(null);// GUI comes in center
                HR.setTitle("HR MANAGEMENT SYSTEM");
                //HR.setSize(600,600);
                HR.setVisible(true);
            }
            catch(Exception e) {System.out.println("Exception Generated:"+e);}
            finally 
            {
                try
                {
                if(rs!=null) rs.close();
                if(st!=null) st.close();
                if(con!=null) con.close();
                }
               catch(SQLException sqle) {System.out.println(sqle);}
            } // end of finally  
        }
    }//GEN-LAST:event_LoginBActionPerformed

    private void ResetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBActionPerformed
        // TODO add your handling code here:
        AdminIdTF.setText("");
        PasswordTF.setText("");
        AdminIdTF.requestFocus();
    }//GEN-LAST:event_ResetBActionPerformed

    private void PasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Login().setVisible(true);
                
                JFrame.setDefaultLookAndFeelDecorated(true);
                Login L1=new Login();
                L1.setTitle("LOGIN");
                L1.setVisible(true);
                L1.setLocationRelativeTo(null);
                L1.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminIdL;
    private javax.swing.JTextField AdminIdTF;
    private javax.swing.JButton LoginB;
    private javax.swing.JLabel PasswordL;
    private javax.swing.JPasswordField PasswordTF;
    private javax.swing.JButton ResetB;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
