/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lekha khobrekar
 */
import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.sql.*;
import javax.swing.JOptionPane;

public class NewEmployee extends javax.swing.JFrame {

Connection con;
Statement st;
ResultSet rs;
PreparedStatement pst;

    /**
     * Creates new form NewEmployee
     */
    public NewEmployee() {
        initComponents();
        DBConnect dbc=new DBConnect();
        con=dbc.Connect();
        System.out.println("DB Connected");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainP = new javax.swing.JPanel();
        NameNeL = new javax.swing.JLabel();
        PhoneNeL = new javax.swing.JLabel();
        EmailNeL = new javax.swing.JLabel();
        PostNeL = new javax.swing.JLabel();
        DOBNeL = new javax.swing.JLabel();
        SkillsNeL = new javax.swing.JLabel();
        SalaryNeL = new javax.swing.JLabel();
        AddressNeL = new javax.swing.JLabel();
        NameNeTF = new javax.swing.JTextField();
        PhoneNeTF = new javax.swing.JTextField();
        EmailNeTF = new javax.swing.JTextField();
        DOBNeTF = new javax.swing.JTextField();
        PostNeTF = new javax.swing.JTextField();
        SkillsNeTF = new javax.swing.JTextField();
        SalaryNeTF = new javax.swing.JTextField();
        AddressNeTF = new javax.swing.JTextField();
        SubmitNeB = new javax.swing.JButton();
        ResetNeB = new javax.swing.JButton();
        HomeNeB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Employee", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 1, 20))); // NOI18N

        NameNeL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        NameNeL.setText("Name");

        PhoneNeL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        PhoneNeL.setText("Phone Number");

        EmailNeL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EmailNeL.setText("Email");

        PostNeL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        PostNeL.setText("POST");

        DOBNeL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        DOBNeL.setText("DOB");

        SkillsNeL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        SkillsNeL.setText("Skills");

        SalaryNeL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        SalaryNeL.setText("Salary");

        AddressNeL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        AddressNeL.setText("Address");

        NameNeTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        NameNeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameNeTFActionPerformed(evt);
            }
        });

        PhoneNeTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        PhoneNeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNeTFActionPerformed(evt);
            }
        });

        EmailNeTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EmailNeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailNeTFActionPerformed(evt);
            }
        });

        DOBNeTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        DOBNeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBNeTFActionPerformed(evt);
            }
        });

        PostNeTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        PostNeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostNeTFActionPerformed(evt);
            }
        });

        SkillsNeTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        SkillsNeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkillsNeTFActionPerformed(evt);
            }
        });

        SalaryNeTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        SalaryNeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryNeTFActionPerformed(evt);
            }
        });

        AddressNeTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        AddressNeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressNeTFActionPerformed(evt);
            }
        });

        SubmitNeB.setText("Submit");
        SubmitNeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitNeBActionPerformed(evt);
            }
        });

        ResetNeB.setText("Reset");
        ResetNeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetNeBActionPerformed(evt);
            }
        });

        HomeNeB.setText("Home");
        HomeNeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeNeBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPLayout = new javax.swing.GroupLayout(MainP);
        MainP.setLayout(MainPLayout);
        MainPLayout.setHorizontalGroup(
            MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPLayout.createSequentialGroup()
                .addGroup(MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneNeL)
                            .addComponent(NameNeL)
                            .addComponent(EmailNeL)
                            .addComponent(DOBNeL)
                            .addComponent(PostNeL)
                            .addComponent(SkillsNeL)
                            .addComponent(SalaryNeL)
                            .addComponent(AddressNeL)))
                    .addGroup(MainPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HomeNeB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPLayout.createSequentialGroup()
                        .addComponent(SubmitNeB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ResetNeB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPLayout.createSequentialGroup()
                        .addGroup(MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PostNeTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddressNeTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(SalaryNeTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SkillsNeTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DOBNeTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameNeTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneNeTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailNeTF))
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MainPLayout.setVerticalGroup(
            MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameNeL)
                    .addComponent(NameNeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNeL)
                    .addComponent(PhoneNeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailNeL)
                    .addComponent(EmailNeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBNeL)
                    .addComponent(DOBNeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PostNeL)
                    .addComponent(PostNeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SkillsNeL)
                    .addComponent(SkillsNeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalaryNeL)
                    .addComponent(SalaryNeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressNeL)
                    .addComponent(AddressNeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(MainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitNeB)
                    .addComponent(ResetNeB)
                    .addComponent(HomeNeB))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 40, Short.MAX_VALUE)
                    .addComponent(MainP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 41, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 21, Short.MAX_VALUE)
                    .addComponent(MainP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 21, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameNeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameNeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameNeTFActionPerformed

    private void PhoneNeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNeTFActionPerformed

    private void DOBNeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBNeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBNeTFActionPerformed

    private void SubmitNeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitNeBActionPerformed
        // TODO add your handling code here:
        try{
            st = con.createStatement();
            String sqlstr="select * from employee";
            rs = st.executeQuery(sqlstr);
            String insert_e_sql="insert into employee(empName,phoneNo,email,dateBirth,empPOST,empSkills,empSalary,empAddress)"+
            "values(?,?,?,?,?,?,?,?)";
            //System.out.println(insert_e_sql);

            pst=con.prepareStatement(insert_e_sql);
            //pst.setString(1,eId);//1 specifies the first parameter in the query
            pst.setString(1,NameNeTF.getText());
            pst.setString(2,PhoneNeTF.getText());
            pst.setString(3,EmailNeTF.getText());
            pst.setString(4,DOBNeTF.getText());
            pst.setString(5,PostNeTF.getText());
            pst.setString(6,SkillsNeTF.getText());
            pst.setFloat(7,Float.parseFloat(SalaryNeTF.getText()));
            pst.setString(8,AddressNeTF.getText());
            int inserted_rows=pst.executeUpdate();
            System.out.println(inserted_rows);
            JOptionPane.showMessageDialog(this,"Employee Added Successfully!!!");
        }
        catch(Exception e) {System.out.println("Exception Generated:"+e);}
    }//GEN-LAST:event_SubmitNeBActionPerformed

    private void ResetNeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetNeBActionPerformed
        // TODO add your handling code here:
        NameNeTF.setText("");
        PhoneNeTF.setText("");
        EmailNeTF.setText("");
        DOBNeTF.setText("");
        PostNeTF.setText("");
        SkillsNeTF.setText("");
        SalaryNeTF.setText("");
        AddressNeTF.setText("");
    }//GEN-LAST:event_ResetNeBActionPerformed

    private void HomeNeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeNeBActionPerformed
        // TODO add your handling code here
        this.setVisible(false);
        HRManagement HR= new HRManagement();
        HR.setLocationRelativeTo(null);
        HR.setTitle("HR Management System");
        HR.setVisible(true);
    }//GEN-LAST:event_HomeNeBActionPerformed

    private void EmailNeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailNeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailNeTFActionPerformed

    private void PostNeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostNeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PostNeTFActionPerformed

    private void SkillsNeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkillsNeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SkillsNeTFActionPerformed

    private void SalaryNeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryNeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryNeTFActionPerformed

    private void AddressNeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressNeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressNeTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressNeL;
    private javax.swing.JTextField AddressNeTF;
    private javax.swing.JLabel DOBNeL;
    private javax.swing.JTextField DOBNeTF;
    private javax.swing.JLabel EmailNeL;
    private javax.swing.JTextField EmailNeTF;
    private javax.swing.JButton HomeNeB;
    private javax.swing.JPanel MainP;
    private javax.swing.JLabel NameNeL;
    private javax.swing.JTextField NameNeTF;
    private javax.swing.JLabel PhoneNeL;
    private javax.swing.JTextField PhoneNeTF;
    private javax.swing.JLabel PostNeL;
    private javax.swing.JTextField PostNeTF;
    private javax.swing.JButton ResetNeB;
    private javax.swing.JLabel SalaryNeL;
    private javax.swing.JTextField SalaryNeTF;
    private javax.swing.JLabel SkillsNeL;
    private javax.swing.JTextField SkillsNeTF;
    private javax.swing.JButton SubmitNeB;
    // End of variables declaration//GEN-END:variables
}
