/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lekha khobrekar
 */
import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SearchEmployee extends javax.swing.JFrame{
    /**
     * Creates new form SearchEmployee
     */
    Connection con;
    ResultSet rs;
    Statement st;
    PreparedStatement ps;
   
    public SearchEmployee() {
        initComponents();
        DBConnect dbc=new DBConnect();
        con=dbc.Connect();
        System.out.println("DB Connected");       
        try{
            st = con.createStatement();
            String sqlstr="select empId,empName,phoneNo,email,empAddress from employee";
            rs = st.executeQuery(sqlstr);
        
            String [] col={"ID","Name","PhoneNo","Email","Address"};
            int ID=0;
            String Name="";
            String PhoneNo="";
            String Email="";
            String Address="";
            while(rs.next())
            {
                ID=Integer.parseInt(rs.getString("empId"));
                Name=rs.getString("empName");
                PhoneNo=rs.getString("phoneNo");
                Email=rs.getString("email");
                Address=rs.getString("empAddress");
                DefaultTableModel model= (DefaultTableModel) EmployeeT.getModel();
                model.setColumnIdentifiers(col);
                
                model.addRow(new Object[]{ID,Name,PhoneNo,Email,Address});
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchP = new javax.swing.JPanel();
        empNameTF = new javax.swing.JTextField();
        SearchB = new javax.swing.JButton();
        ScrollPane = new javax.swing.JScrollPane();
        EmployeeT = new javax.swing.JTable();
        empNameL = new javax.swing.JLabel();
        empPostL = new javax.swing.JLabel();
        empPostTF = new javax.swing.JTextField();
        Home2B = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchT1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Employee", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 1, 20))); // NOI18N

        empNameTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        empNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameTFActionPerformed(evt);
            }
        });

        SearchB.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        SearchB.setText("Search");
        SearchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBActionPerformed(evt);
            }
        });

        EmployeeT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EmployeeT.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        EmployeeT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ScrollPane.setViewportView(EmployeeT);

        empNameL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        empNameL.setText("Employee Name");

        empPostL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        empPostL.setText("Employee Post");

        empPostTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        empPostTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPostTFActionPerformed(evt);
            }
        });

        Home2B.setText("Home");
        Home2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home2BActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        jLabel1.setText("Details:");

        SearchT1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(SearchT1);

        javax.swing.GroupLayout SearchPLayout = new javax.swing.GroupLayout(SearchP);
        SearchP.setLayout(SearchPLayout);
        SearchPLayout.setHorizontalGroup(
            SearchPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchPLayout.createSequentialGroup()
                        .addGroup(SearchPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(empNameL, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empPostL, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(SearchPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SearchPLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(empNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addGroup(SearchPLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(empPostTF)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchB, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SearchPLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(SearchPLayout.createSequentialGroup()
                        .addGroup(SearchPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Home2B, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        SearchPLayout.setVerticalGroup(
            SearchPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(SearchPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empNameL))
                .addGap(18, 18, 18)
                .addGroup(SearchPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empPostL)
                    .addComponent(empPostTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Home2B)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(SearchP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SearchP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNameTFActionPerformed

    private void SearchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBActionPerformed
        // TODO add your handling code here:
                
            Function f1=new Function();
            rs=null;
            rs=f1.find(empNameTF.getText());
            String [] col={"ID","Name","PhoneNo","Email","Address"};
            int ID=0;
            String Name="";
            String PhoneNo="";
            String Email="";
            String Address="";

        try{
            
            if(rs.next())
            {
                    ID=Integer.parseInt(rs.getString("empId"));
                    Name=rs.getString("empName");
                    PhoneNo=rs.getString("phoneNo");
                    Email=rs.getString("email");
                    Address=rs.getString("empAddress");
                    DefaultTableModel model= (DefaultTableModel) SearchT1.getModel();
                    model.setColumnIdentifiers(col);
                    model.addRow(new Object[]{ID,Name,PhoneNo,Email,Address});
            }   
            else
            {
                System.out.println("NO DATA");
            }
        }
        catch(Exception e){
            System.out.println("Exception:"+e.getMessage());
        }
    }//GEN-LAST:event_SearchBActionPerformed

    private void Home2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home2BActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HRManagement HR= new HRManagement();
        HR.setLocationRelativeTo(null);
        HR.setTitle("HR Management System");
        HR.setVisible(true);
    }//GEN-LAST:event_Home2BActionPerformed

    private void empPostTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPostTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPostTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public class Function
    {
        public ResultSet find(String s)
        {
            try{
            st = con.createStatement();
            ps=con.prepareStatement("select empId,empName,phoneNo,email,empAddress from employee where empName = ?");
            ps.setString(1,s);
            rs = ps.executeQuery();
            }
            catch(Exception e)
            {
                System.out.println(e.getMessage());
            }
           return rs;
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmployeeT;
    private javax.swing.JButton Home2B;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton SearchB;
    private javax.swing.JPanel SearchP;
    private javax.swing.JTable SearchT1;
    private javax.swing.JLabel empNameL;
    private javax.swing.JTextField empNameTF;
    private javax.swing.JLabel empPostL;
    private javax.swing.JTextField empPostTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
