/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lekha khobrekar
 */
import java.awt.Font;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class UpdateEmployee extends javax.swing.JFrame {

    /**
     * Creates new form UpdateEmployee
     */
    
    Connection con;
    ResultSet rs;
    Statement st;
    PreparedStatement ps;
    
    public UpdateEmployee() {
        initComponents();
        DBConnect dbc=new DBConnect();
        con=dbc.Connect();
        System.out.println("DB Connected");       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateP = new javax.swing.JPanel();
        Home3B = new javax.swing.JButton();
        ENameL = new javax.swing.JLabel();
        EPostL = new javax.swing.JLabel();
        ENameTF = new javax.swing.JTextField();
        EPostTF = new javax.swing.JTextField();
        DeleteB = new javax.swing.JButton();
        UpdateB = new javax.swing.JButton();
        EDetailL = new javax.swing.JLabel();
        SearchB = new javax.swing.JButton();
        EIdL = new javax.swing.JLabel();
        EName2L = new javax.swing.JLabel();
        EPhoneL = new javax.swing.JLabel();
        EEmailL = new javax.swing.JLabel();
        EAddressL = new javax.swing.JLabel();
        EIdTF = new javax.swing.JTextField();
        EName2TF = new javax.swing.JTextField();
        EPhoneTF = new javax.swing.JTextField();
        EEmailTF = new javax.swing.JTextField();
        EAddressTF = new javax.swing.JTextField();
        ResetB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UpdateP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Employee", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 1, 20))); // NOI18N

        Home3B.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        Home3B.setText("Home");
        Home3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home3BActionPerformed(evt);
            }
        });

        ENameL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        ENameL.setText("Employee Name");

        EPostL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EPostL.setText("Employee Post");

        ENameTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        ENameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENameTFActionPerformed(evt);
            }
        });

        EPostTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EPostTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPostTFActionPerformed(evt);
            }
        });

        DeleteB.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        DeleteB.setText("Delete");
        DeleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBActionPerformed(evt);
            }
        });

        UpdateB.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        UpdateB.setText("Update");
        UpdateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBActionPerformed(evt);
            }
        });

        EDetailL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EDetailL.setText("Details:");

        SearchB.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        SearchB.setText("Search");
        SearchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBActionPerformed(evt);
            }
        });

        EIdL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EIdL.setText("ID");

        EName2L.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EName2L.setText("Name");

        EPhoneL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EPhoneL.setText("Phone No");

        EEmailL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EEmailL.setText("Email");

        EAddressL.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EAddressL.setText("Address");

        EIdTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        EIdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIdTFActionPerformed(evt);
            }
        });

        EName2TF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N

        EPhoneTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N

        EEmailTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N

        EAddressTF.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N

        ResetB.setText("Reset");
        ResetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdatePLayout = new javax.swing.GroupLayout(UpdateP);
        UpdateP.setLayout(UpdatePLayout);
        UpdatePLayout.setHorizontalGroup(
            UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatePLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ResetB)
                        .addGap(18, 18, 18)
                        .addComponent(Home3B)
                        .addGap(6, 6, 6))
                    .addGroup(UpdatePLayout.createSequentialGroup()
                        .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EPostL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ENameL, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ENameTF)
                            .addComponent(EPostTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(SearchB)
                        .addContainerGap())
                    .addGroup(UpdatePLayout.createSequentialGroup()
                        .addComponent(EDetailL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(UpdatePLayout.createSequentialGroup()
                        .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UpdatePLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EIdL, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(EName2L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EPhoneL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EEmailL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EAddressL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EIdTF)
                                    .addComponent(EName2TF)
                                    .addComponent(EPhoneTF)
                                    .addComponent(EEmailTF, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(EAddressTF)))
                            .addGroup(UpdatePLayout.createSequentialGroup()
                                .addComponent(DeleteB)
                                .addGap(18, 18, 18)
                                .addComponent(UpdateB)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        UpdatePLayout.setVerticalGroup(
            UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatePLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ENameL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ENameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EPostL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EPostTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchB))
                .addGap(50, 50, 50)
                .addComponent(EDetailL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EIdL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EName2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EName2L, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EPhoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EPhoneL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EEmailL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EAddressL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteB)
                    .addComponent(UpdateB))
                .addGap(39, 39, 39)
                .addGroup(UpdatePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home3B)
                    .addComponent(ResetB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(UpdateP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(UpdateP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home3BActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HRManagement HR= new HRManagement();
        HR.setLocationRelativeTo(null);
        HR.setTitle("HR Management System");
        HR.setVisible(true);
    }//GEN-LAST:event_Home3BActionPerformed

    private void ENameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ENameTFActionPerformed

    private void EPostTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPostTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPostTFActionPerformed

    private void DeleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBActionPerformed
        // TODO add your handling code here:
        try{
            st = con.createStatement();
            String sqlstr="delete from employee where empName='"+ENameTF.getText()+"'";
            st.executeUpdate(sqlstr);
            JOptionPane.showMessageDialog(this,"Delete Successful!!!");
            }
            catch(Exception e)
            {
                System.out.println(e.getMessage());
            }
    }//GEN-LAST:event_DeleteBActionPerformed

    private void UpdateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBActionPerformed
        // TODO add your handling code here:
        try{
            st = con.createStatement();
            String sqlstr="Update employee set empName='"+EName2TF.getText()+"',phoneNo='"+EPhoneTF.getText()+"',email='"+EEmailTF.getText()+"',empAddress='"+EAddressTF.getText()+"',empId="+EIdTF.getText()+" where empName ='"+ENameTF.getText()+"'";
            st.executeUpdate(sqlstr);
            JOptionPane.showMessageDialog(this,"Update Successful!!!");
            }
            catch(Exception e)
            {
                System.out.println(e.getMessage());
            }
    }//GEN-LAST:event_UpdateBActionPerformed

    private void SearchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBActionPerformed
        // TODO add your handling code here:
        Function f1=new Function();
            rs=null;
            rs=f1.find(ENameTF.getText());
            
            int ID=0;
            String Name="";
            String PhoneNo="";
            String Email="";
            String Address="";

        try{
            
            if(rs.next())
            {
                    ID=Integer.parseInt(rs.getString("empId"));
                    Name=rs.getString("empName");
                    PhoneNo=rs.getString("phoneNo");
                    Email=rs.getString("email");
                    Address=rs.getString("empAddress");
                    
                    EIdTF.setText(String.valueOf(ID));
                    EName2TF.setText(Name);
                    EPhoneTF.setText(PhoneNo);
                    EEmailTF.setText(Email);
                    EAddressTF.setText(Address);
            }   
            else
            {
                System.out.println("NO DATA");
            }
        }
        catch(Exception e){
            System.out.println("Exception:"+e.getMessage());
        }
    }//GEN-LAST:event_SearchBActionPerformed

    private void EIdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EIdTFActionPerformed

    private void ResetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBActionPerformed
        // TODO add your handling code here:
        ENameTF.setText("");
        EPostTF.setText("");
        EIdTF.setText("");
        EName2TF.setText("");
        EPhoneTF.setText("");
        EEmailTF.setText("");
        EAddressTF.setText("");
    }//GEN-LAST:event_ResetBActionPerformed

    public class Function
    {
        public ResultSet find(String s)
        {
            try{
            st = con.createStatement();
            ps=con.prepareStatement("select empId,empName,phoneNo,email,empAddress from employee where empName = ?");
            ps.setString(1,s);
            rs = ps.executeQuery();
            }
            catch(Exception e)
            {
                System.out.println(e.getMessage());
            }
           return rs;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteB;
    private javax.swing.JLabel EAddressL;
    private javax.swing.JTextField EAddressTF;
    private javax.swing.JLabel EDetailL;
    private javax.swing.JLabel EEmailL;
    private javax.swing.JTextField EEmailTF;
    private javax.swing.JLabel EIdL;
    private javax.swing.JTextField EIdTF;
    private javax.swing.JLabel EName2L;
    private javax.swing.JTextField EName2TF;
    private javax.swing.JLabel ENameL;
    private javax.swing.JTextField ENameTF;
    private javax.swing.JLabel EPhoneL;
    private javax.swing.JTextField EPhoneTF;
    private javax.swing.JLabel EPostL;
    private javax.swing.JTextField EPostTF;
    private javax.swing.JButton Home3B;
    private javax.swing.JButton ResetB;
    private javax.swing.JButton SearchB;
    private javax.swing.JButton UpdateB;
    private javax.swing.JPanel UpdateP;
    // End of variables declaration//GEN-END:variables
}
